### PR TITLE
✨ Optimize users API responses

### PR DESCRIPTION
**Pull request by lmachens**
Based on this feedback, I like to optimize the API responses.
https://github.com/lmachens/photoplay/pull/81#discussion_r644581710
https://github.com/lmachens/photoplay/pull/81#discussion_r644582032

### CODE REVIEW

**Review by mpagels — APPROVED** [review]

**Review by lajanzen — APPROVED** [review]
🚀

**Review by daebert — APPROVED** [review]
LGTM 🚀

**Review by jujuzitroni — APPROVED** [review]
lgtm

**Review by Dev-dfm — APPROVED** [review]
lgtm! 🚀

**Review by Dev-dfm — APPROVED** [review]
lgtm 🚀

**Review by SGierszewski — APPROVED** [review]
Perfect, thx! 🥳

**Comment by SGierszewski** [comment]
fixes #82

**Pull request merged**
