### PR TITLE
add navBar import

### PR DESCRIPTION
**Pull request by daebert**
Add NavBar Import

### CODE REVIEW

**Review by J-Bannach — APPROVED** [review]
🚀  thanks

**Review by mpagels — APPROVED** [review]
very good

**Review by SGierszewski — APPROVED** [review]
Great, thank you! 👍

**Review by Dev-dfm — APPROVED** [review]
👍

**Review by jujuzitroni — APPROVED** [review]
thank you 🥇

**Review by l-goede — APPROVED** [review]
thank you!!!

**Review by dhnazarenko — APPROVED** [review]
lgtm 🚀

**Review by Niklas-Schaefers — APPROVED** [review]

**Pull request merged**
