### PR TITLE
♻️ Rename CSS variables

### PR DESCRIPTION
**Pull request by lmachens**
## What is the current behavior?

Issue Number: #113 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Storybook (`npm run stroybook`) was run
- [x] Server (`npm run server:dev`) was run
- [x] Vite (`npm run client:dev`) was run

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?

New naming convention for CSS variables.

## Other information

Autocompletion works much better now:
image

### CODE REVIEW

**Review by roscha80 — APPROVED** [review]
Nice and smart change. With autocomplete it makes totaly sence.

**Comment by anniviz** [comment]
How did you make the auto completion work that way? are you using a special extension?

**Review by anniviz — APPROVED** [review]
Looks good to me, couldn't find any typo 😉
I like your naming convention (I did a bit of research for this and ended up with the same)

**Review by Niklas-Schaefers — APPROVED** [review]
lgtm 🚀

**Review by Dev-dfm — APPROVED** [review]
lgtm 🚀

**Comment by lmachens** [comment]
> How did you make the auto completion work that way? are you using a special extension?

It should work in CSS files without an extension.

**Pull request merged**
