### PR TITLE
💄 Make homescreen page scrollable

### LINKED ISSUE #58: Can not scroll to "watching" list on homescreen
### What?

I like to see the watching list on the homescreen, but I am not able to scroll to that section.

image

### Reproduce

You can run storybook (`npm run storybook`) and visit Homescreen/Default story. 
I used the "small mobile" screen in Storybook.

### Possible solutions

1) Add a bottom padding of the same height as the footer.
2) Do not absolute/fixed position the footer

### PR DESCRIPTION
**Pull request by Dev-dfm**
fixes #58

Removed navBar style, set height to auto

### CODE REVIEW

**Review by dhnazarenko — COMMENTED** [review]
lgtm 🚀

**Review by Maurizio-F — COMMENTED** [review]
lgtm 💯

**Review by lmachens — APPROVED** [review]
Good job. 
The pull request title should tell us, why you removed this style and set height to auto. I can see the changes in the commit, but I don't know why you did that in the commit history.

**Review by Niklas-Schaefers — APPROVED** [review]
lgtm 🚀

**Review by lajanzen — APPROVED** [review]
Looks great! 🚀

**Review by l-goede — APPROVED** [review]
great job

**Review by daebert — APPROVED** [review]
lgtm!

**Review by infoucarsinan — APPROVED** [review]

**Review by tmh9x — APPROVED** [review]

**Review by roabram — APPROVED** [review]
lgtm! 👍

**Review by MaxMuecket — APPROVED** [review]
lgtm

**Review by J-Bannach — APPROVED** [review]

**Review by jujuzitroni — APPROVED** [review]
nice 👍

**Review by mpagels — APPROVED** [review]

**Review by JGieseWeb — APPROVED** [review]
Good fix 😁

**Review by Niklas-Schaefers — APPROVED** [review]
lgtm 🚀

**Review by SGierszewski — APPROVED** [review]
LGTM 🥳

**Pull request merged**
