### PR TITLE
👷 Add production build

### PR DESCRIPTION
**Pull request by lmachens**
### Build guides
https://vitejs.dev/guide/build.html
https://storybook.js.org/docs/react/workflows/publish-storybook#build-storybook-as-a-static-web-application
https://expressjs.com/en/starter/static-files.html

### CODE REVIEW

**Review by mpagels — APPROVED** [review]
I like the size of the pull request and looks good to me.

**Review by roabram — APPROVED** [review]
lgtm 👍

**Review by Dev-dfm — APPROVED** [review]
lgtm 💯

**Review by dhnazarenko — APPROVED** [review]
lgtm 🚀

**Pull request merged**
