### PR TITLE
🚛  Rename Page to Register and move it to pages folder

### LINKED ISSUE #59: Move Register page into pages folder
The Register files are in a 'Page' folder. They should be moved to the 'Pages' folder and the 'Page' folder should be removed.

### PR DESCRIPTION
**Pull request by Maurizio-F**
fixes #59

### CODE REVIEW

**Review by dhnazarenko — APPROVED** [review]
lgtm 🚀

**Review by Dev-dfm — APPROVED** [review]
lgtm! 🚀

**Review by lajanzen — APPROVED** [review]
LGTM 🚀

**Review by daebert — APPROVED** [review]
lgtm!

**Review by infoucarsinan — APPROVED** [review]

**Review by mpagels — APPROVED** [review]

**Review by J-Bannach — APPROVED** [review]

**Review by tmh9x — APPROVED** [review]

**Review by jujuzitroni — APPROVED** [review]
👍

**Review by SGierszewski — APPROVED** [review]
Great, thx! 💯

**Review by roabram — APPROVED** [review]
lgtm 👍

**Review by JGieseWeb — APPROVED** [review]
lgtm ☺

**Pull request merged**
