### PR TITLE
♻️ Refactor server

### PR DESCRIPTION
**Pull request by lmachens**
The API response type are useful in the client too, thus, I moved the types to a new module.

In addition, the error handling is moved to the server.js.

### CODE REVIEW

**Review by Dev-dfm — APPROVED** [review]
lgtm 💯

**Review by fgottesmann — APPROVED** [review]
lgtm! 👍

**Review by Maurizio-F — COMMENTED** [review]
lgtm! 🥇

**Review by dhnazarenko — COMMENTED** [review]
lgtm 🚀

**Review by MaxMuecket — APPROVED** [review]
lgtm 🏅

**Comment by Niklas-Schaefers** [comment]
lgtm  🚀

**Review by daebert — COMMENTED** [review]
Good work!

**Review by SGierszewski — APPROVED** [review]
LGTM 👍

**Review by tmh9x — APPROVED** [review]

**Review by jujuzitroni — APPROVED** [review]
lgtm

**Comment by J-Bannach** [comment]
lgtm

**Pull request merged**
