### PR TITLE
✨ Replace download icon with favorite icon

### PR DESCRIPTION
**Pull request by jujuzitroni**
part of issue #10

### CODE REVIEW

**Review by J-Bannach — APPROVED** [review]
🚀

**Review by Dev-dfm — APPROVED** [review]
lgtm 💯

**Review by daebert — APPROVED** [review]
lgtm

**Review by tmh9x — APPROVED** [review]

**Review by infoucarsinan — APPROVED** [review]

**Review by roabram — APPROVED** [review]
lgtm

**Review by JGieseWeb — APPROVED** [review]
🎉lgtm

**Review by MaxMuecket — APPROVED** [review]
🏆🥇

**Review by Niklas-Schaefers — APPROVED** [review]
lgtm

**Review by dhnazarenko — APPROVED** [review]
lgtm 🚀

**Pull request merged**
