### PR TITLE
♻️ Implement api to TVShowDetails

### LINKED ISSUE #64: resize TV Show Details image
### Problem:

The image is way too big and blurred.

image

### Possible solution:

- give image a max size to prevent this

### PR DESCRIPTION
**Pull request by tmh9x**
fixes #64

- implement image from api
- removed static image

### CODE REVIEW

**Review by dhnazarenko — APPROVED** [review]
lgtm 🚀

**Review by Dev-dfm — COMMENTED** [review]
lgtm 🚀

**Review by lajanzen — APPROVED** [review]

**Review by roabram — APPROVED** [review]
lgtm

**Review by jujuzitroni — APPROVED** [review]
🚀

**Review by Niklas-Schaefers — APPROVED** [review]
lgtm 🚀

**Review by daebert — APPROVED** [review]
great

**Review by MaxMuecket — APPROVED** [review]
lgtm

**Review by SGierszewski — APPROVED** [review]
Great work! 🚀

**Review by J-Bannach — APPROVED** [review]

**Review by JGieseWeb — APPROVED** [review]
Good work ✨

**Review by mpagels — APPROVED** [review]

**Comment by l-goede** [comment]
lgtm

**Pull request merged**
