### PR TITLE
✨ Implement MultiSearch Endpoint

### PR DESCRIPTION
**Pull request by phlgr**
Backend part of #13

### CODE REVIEW

**Review by lmachens — COMMENTED** [review]
Good job! 
Can you transform the data like we did for movies and popular movies to send only required fields to our client?

**Review by Dev-dfm — APPROVED** [review]
lgtm 💯

**Review by J-Bannach — APPROVED** [review]
lgtm 🤖

**Review by dhnazarenko — APPROVED** [review]
LGTM 🚀

**Review by Maurizio-F — COMMENTED** [review]
lgtm! 💯

**Pull request merged**
