### PR TITLE
✨Create Issue/Pull Request templates

### LINKED ISSUE #61: Create Issue/Pull Request templates
This project is growing fast 🚀.
Let us use [issue and pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) for a more structured documentation.

[github-issue-templates](https://github.com/stevemao/github-issue-templates) has a good collection with sample templates.

### PR DESCRIPTION
**Pull request by JGieseWeb**
fixes #61

### CODE REVIEW

**Review by roabram — APPROVED** [review]
lgtm 💯

**Review by dhnazarenko — APPROVED** [review]
lgtm 🚀

**Review by lajanzen — APPROVED** [review]
Nice!!!

**Review by infoucarsinan — APPROVED** [review]

**Review by Dev-dfm — APPROVED** [review]
lgtm 💯

**Review by tmh9x — APPROVED** [review]

**Review by daebert — APPROVED** [review]
Helpful, thanks!

**Review by Niklas-Schaefers — APPROVED** [review]
lgtm 🚀

**Review by J-Bannach — APPROVED** [review]
Really helpful, thanks!

**Review by Maurizio-F — APPROVED** [review]
lgtm 👍

**Review by SGierszewski — APPROVED** [review]
💯

**Pull request merged**
