### PR TITLE
Rename Cast Component

### LINKED ISSUE #74: Rename Cast Page
The Cast Page should be renamed to avoid confusion with the Cast component.

### PR DESCRIPTION
**Pull request by Niklas-Schaefers**
fixes #74

### CODE REVIEW

**Review by Maurizio-F — COMMENTED** [review]
lgtm 👍

**Review by Dev-dfm — APPROVED** [review]
lgtm 💯

**Review by lajanzen — APPROVED** [review]

**Comment by l-goede** [comment]
looks very good! Maybe change the title of the pull request for a more specific understanding of the issue 🦖

**Review by daebert — APPROVED** [review]
good work!

**Review by J-Bannach — APPROVED** [review]

**Review by roabram — APPROVED** [review]
lgtm 👍

**Review by tmh9x — APPROVED** [review]

**Review by dhnazarenko — APPROVED** [review]

**Review by SGierszewski — APPROVED** [review]
💯

**Review by infoucarsinan — APPROVED** [review]

**Review by infoucarsinan — APPROVED** [review]

**Review by JGieseWeb — APPROVED** [review]
Good work 👏

**Review by roabram — APPROVED** [review]
lgtm

**Review by jujuzitroni — APPROVED** [review]

**Pull request merged**
