### PR TITLE
🎨 Add the max-width to all Pages

### PR DESCRIPTION
**Pull request by JGieseWeb**
margin: 0 auto;

### CODE REVIEW

**Review by dhnazarenko — APPROVED** [review]
lgtm 🚀

**Review by lajanzen — COMMENTED** [review]
Great work 🧸

**Review by daebert — APPROVED** [review]
good!

**Review by J-Bannach — APPROVED** [review]

**Review by tmh9x — APPROVED** [review]

**Review by Niklas-Schaefers — APPROVED** [review]
lgtm 🚀

**Review by mpagels — APPROVED** [review]

**Review by MaxMuecket — APPROVED** [review]
lgtm

**Review by jujuzitroni — APPROVED** [review]
lgtm 🚀

**Review by Dev-dfm — APPROVED** [review]
lgtm 🚀

**Review by roabram — APPROVED** [review]
lgtm :)

**Review by l-goede — APPROVED** [review]
great job!

**Review by SGierszewski — APPROVED** [review]
Well done! 🥳

**Review by Maurizio-F — APPROVED** [review]

**Review by infoucarsinan — APPROVED** [review]

**Pull request merged**
