### PR TITLE
🎨 Add useFetch hook

### PR DESCRIPTION
**Pull request by lmachens**
Example usage:

```ts
const { data: movie, isLoading, errorMessage } = useFetch<Movie>();
```

### CODE REVIEW

**Review by dhnazarenko — COMMENTED** [review]
lgtm 🚀

**Review by SGierszewski — APPROVED** [review]
LGTM 🚀

**Review by jujuzitroni — APPROVED** [review]
lgtm :)

**Review by MaxMuecket — APPROVED** [review]
lgtm 🚀

**Review by Dev-dfm — APPROVED** [review]
Great work! 💯

**Review by Maurizio-F — COMMENTED** [review]
lgtm 👍

**Review by roabram — APPROVED** [review]
lgtm

**Comment by J-Bannach** [comment]
lgtm

**Pull request merged**
