### PR TITLE
💄 Add bottom padding and hide scrollbar

### LINKED ISSUE #60: Cast Page
Check and hide Scrollbar on "known for"-slider.

Large mobile view on storybook. 

image

### PR DESCRIPTION
**Pull request by dhnazarenko**
fixes #60

+ Add bottom padding on main container.

### CODE REVIEW

**Review by Maurizio-F — COMMENTED** [review]
Good job! 👍

**Review by lmachens — APPROVED** [review]
♪(^∇^*)

**Review by l-goede — APPROVED** [review]
looks good!!!

**Review by Dev-dfm — APPROVED** [review]
lgtm 💯

**Review by lajanzen — APPROVED** [review]
Looks great! 🚀

**Review by Niklas-Schaefers — APPROVED** [review]
lgtm 🚀

**Review by daebert — APPROVED** [review]
great

**Review by mpagels — APPROVED** [review]

**Review by tmh9x — APPROVED** [review]

**Review by J-Bannach — APPROVED** [review]

**Review by MaxMuecket — APPROVED** [review]
lgtm 🚀

**Review by jujuzitroni — APPROVED** [review]
🚀

**Review by infoucarsinan — APPROVED** [review]

**Review by Niklas-Schaefers — APPROVED** [review]
lgtm 🚀

**Review by JGieseWeb — APPROVED** [review]
lgtm ☺

**Review by SGierszewski — APPROVED** [review]
Nice job! 🥳

**Review by roabram — APPROVED** [review]
lgtm 👍

**Pull request merged**
