### PR TITLE
🤷‍♂️ Add Placeholder for Homescreen Page

### LINKED ISSUE #83: Find a placeholder image if `posterPath` is not available.
Maybe find a good placeholder if `posterPath` is not available.

_Originally posted by @lmachens in https://github.com/lmachens/photoplay/pull/71#discussion_r644068786_

Lines 36-39:
Problem: If posterPath is not available no image will be shown.

Possible solution:
Find an image to be shown, if posterPath is not available

### PR DESCRIPTION
**Pull request by JGieseWeb**
fixes #83

### CODE REVIEW

**Review by lajanzen — APPROVED** [review]
lgtm 🚀

**Review by Dev-dfm — APPROVED** [review]
lgtm 💯

**Review by daebert — APPROVED** [review]
lgtm

**Review by dhnazarenko — APPROVED** [review]
lgtm 🚀

**Review by J-Bannach — APPROVED** [review]

**Review by Niklas-Schaefers — APPROVED** [review]
lgtm 🚀

**Review by l-goede — APPROVED** [review]
looks fine!

**Review by jujuzitroni — APPROVED** [review]

**Review by SGierszewski — APPROVED** [review]
Great!! 💯

**Review by roabram — APPROVED** [review]
lgtm :)

**Review by tmh9x — APPROVED** [review]

**Review by infoucarsinan — APPROVED** [review]

**Review by MaxMuecket — APPROVED** [review]
lgtm

**Pull request merged**
