### PR TITLE
✨ Implement backend

### PR DESCRIPTION
**Pull request by lmachens**
Part of #48 
A new file `.env` is required with the environment variable `THE_MOVIE_DB_KEY` and `PORT`. Please use your own API key from themoviedb.org. Don't forget to install new dependencies when your checkout this branch.

This pull request implements `/api/movies/popular` for the home page. All other routes are not implemented yet.

A proxy is added to vite and storybook to allow access to the API without CORS issues.

Please verify that the `/api/movies/popular` route is working. You could use `samples.http` for a quick test.

### CODE REVIEW

**Review by dhnazarenko — COMMENTED** [review]
lgtm 🚀

**Review by Maurizio-F — COMMENTED** [review]
It works for me 💯

**Review by Dev-dfm — APPROVED** [review]
lgtm 💯

**Review by daebert — COMMENTED** [review]
Good work!

**Review by MaxMuecket — APPROVED** [review]
lgtm🙌

**Review by SGierszewski — APPROVED** [review]
After fixing some issues with old/new dotenv dependencies, I did a quick test using samples.http and can confirm that the /api/movies/popular route is working fine. Good job, thx! 💯

**Pull request merged**
