### PR TITLE
movieDetails_scroll_cast

### LINKED ISSUE #65: Fix problems with CSS for MovieDetails page
**What?**
1) picture position on page is not correct, it sees there are unnecessary margins set to the image
2) title and genre should be displayed as a layer on top of the picture
3) "Watch now" button is too wide
4) Scroll function is not correctly implemented. Cast cannot be displayed properly.

**Reproduce**
We used "small mobile" view to display the MovieDetails page.

**Possible solutions**
1) Delete picture margins
2) Maybe include a z-index 
3) Change button width
4) Check scroll function in CSS, maybe not set for the whole container?

### PR DESCRIPTION
**Pull request by Niklas-Schaefers**
fixes #65

### CODE REVIEW

**Review by l-goede — APPROVED** [review]
Looks good!

**Review by Maurizio-F — APPROVED** [review]

**Review by Dev-dfm — APPROVED** [review]
lgtm 💯

**Review by fgottesmann — APPROVED** [review]
lgtm

**Review by daebert — APPROVED** [review]
lgtm!

**Review by roabram — APPROVED** [review]
lgtm 👍

**Review by jujuzitroni — APPROVED** [review]

**Review by tmh9x — APPROVED** [review]

**Review by dhnazarenko — APPROVED** [review]
lgtm 🚀

**Pull request merged**
