### PR TITLE
💄 Add global CSS

### PR DESCRIPTION
**Pull request by lmachens**
In preperation of #6, CSS variables are required. This pull request includes:
- load `globals.css` in Storybook
- add CSS variables
- use CSS variables in Button component

Docs:
> Global imported styles
If you have global imported styles, create a file called .storybook/preview.js and import the styles there. The styles will be added by Storybook automatically for all stories.

https://storybook.js.org/docs/react/get-started/setup#render-component-styles

### CODE REVIEW

**Review by SGierszewski — APPROVED** [review]
LGTM 💯

**Review by MaxMuecket — APPROVED** [review]
lgtm

**Review by Dev-dfm — COMMENTED** [review]
lgtm 💯

**Review by tmh9x — APPROVED** [review]

**Review by Maurizio-F — COMMENTED** [review]
lgtm 💯 !

**Review by dhnazarenko — APPROVED** [review]
lgtm 🚀

**Review by lajanzen — APPROVED** [review]
🚀

**Review by jujuzitroni — APPROVED** [review]
lgtm :)

**Review by roabram — APPROVED** [review]

**Review by daebert — APPROVED** [review]

**Review by infoucarsinan — APPROVED** [review]
good work

**Pull request merged**
