### PR TITLE
💄  Align Navbar component left

### LINKED ISSUE #70: NavBar - Align NavBar left
Align NavBar component left, so it fits on pages with global padding

### PR DESCRIPTION
**Pull request by Dev-dfm**
fixes #70

### CODE REVIEW

**Review by dhnazarenko — APPROVED** [review]
lgtm 🚀

**Review by lajanzen — APPROVED** [review]
lgtm 🚀

**Review by daebert — APPROVED** [review]
great!

**Review by tmh9x — APPROVED** [review]

**Review by roabram — APPROVED** [review]
lgtm 👍

**Review by infoucarsinan — APPROVED** [review]

**Review by mpagels — APPROVED** [review]

**Review by jujuzitroni — APPROVED** [review]

**Review by infoucarsinan — APPROVED** [review]

**Review by JGieseWeb — APPROVED** [review]
lgtm 👌

**Review by SGierszewski — APPROVED** [review]
LGTM 🚀

**Review by MaxMuecket — APPROVED** [review]
lgtm 🧸

**Review by Niklas-Schaefers — APPROVED** [review]
lgtm 🚀

**Review by l-goede — APPROVED** [review]
very good!

**Pull request merged**
