### PR TITLE
🚑 Critical style hotfix

### PR DESCRIPTION
**Pull request by phlgr**
Fixes formatting in MovieDetails.module.css

### CODE REVIEW

**Review by jujuzitroni — APPROVED** [review]

**Review by mpagels — APPROVED** [review]
Incredible fix!

**Review by SGierszewski — APPROVED** [review]
👍

**Review by MaxMuecket — APPROVED** [review]
🏆

**Review by dhnazarenko — APPROVED** [review]
lgtm 🚀

**Review by tmh9x — APPROVED** [review]

**Pull request merged**
