### PR TITLE
💄 Resize button and center it

### LINKED ISSUE #66: Resize 'watch now' button on TV show details page
Currently the button is as wide ad the pages allows (see screenshot)
image

It should be smaller in the center of the page: 
image

### PR DESCRIPTION
**Pull request by dhnazarenko**
fixes #66

Delete navBar styles.

### CODE REVIEW

**Review by Dev-dfm — APPROVED** [review]
lgtm! 🚀

**Review by lajanzen — APPROVED** [review]
LGTM 🚀🤓

**Review by daebert — APPROVED** [review]
lgtm!

**Review by l-goede — APPROVED** [review]
looks good!

**Review by J-Bannach — APPROVED** [review]

**Review by mpagels — APPROVED** [review]

**Review by jujuzitroni — APPROVED** [review]
good work 🚀

**Review by roabram — APPROVED** [review]
lgtm 👍

**Review by SGierszewski — APPROVED** [review]
LGTM 💯

**Review by tmh9x — APPROVED** [review]

**Review by infoucarsinan — APPROVED** [review]

**Review by JGieseWeb — APPROVED** [review]
nice small change🎊

**Pull request merged**
